### PR TITLE
Validations

### PR DESCRIPTION
**Pull request by rpire**
## Changes made:
- Created the `_users_form.html.erb` layout and included it in the `root_path`.
- Implemented a `create` method for `Users`.
- Added model validations to existing forms.
- Created unit tests for all models.
- Solved **N+1** problems.

### CODE REVIEW

**Review by Lameck1 — CHANGES_REQUESTED** [review]
Hi @rpire, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
Since I could not find `comments_controller.rb` and `likes_controller.rb` files in `Files Changed` tab, please allow me to leave these required changes in this review summary.
- [x] The create actions in the above-stated controllers do not use flash messages for a successful and not successful path. Please add flash messages as stated in the requirement quoted below:

---
- Add flash messages in the create actions in all your controllers.
---

## Optional suggestions
- NA

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rpire** [comment]
Hello @Lameck1 👋

Thank you for reviewing my work. I didn't think of adding flash messages to `Comments` and `Likes` because they didn't require any validation, but I think you're right. These controllers should also have notifications. 🔎

Once again, thank you for your review. I will make sure to implement the required changes and request another review. 🤓

Cheers and Happy coding to you too! 🐱‍💻

**Review by mke2111 — APPROVED** [review]
### Hi @rpire, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rpire** [comment]
Hello, @mke2111 🙌

Thank you for reviewing my work! I will proceed to merge these changes into the `dev` branch. 🚀

Cheer and Happy coding to you too! 🐱‍💻

**Pull request merged**
