### PR TITLE
Set up

### PR DESCRIPTION
**Pull request by rpire**
## Changes made:
- Initialized a `Ruby on Rails` project.
- Set up Linters in the repository.
- Created the routes in `routes.rb`
- Generated the `Users` and `Posts` controllers.
- Generated views for `Users` and `Posts`.
- Defined actions for `Users` and `Posts`.
- Corrected Linter errors.

### CODE REVIEW

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @rpire, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] README file should have a title and description about the project even if it's one or two-line so that anyone can understand your project. Also, include the steps on how to clone and run the project locally. Currently, you are using the default README which rails generate. Please update that. You can follow [this template](https://github.com/microverseinc/readme-template) as well.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rpire** [comment]
Hello, @Dipeshtwis 👋

It seems that I have completely forgotten to add a `README.md` file at all. 🤦

Thank you for reviewing my work. I will start working on the required changes and request another review.

Cheers! 🤓

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Rubén, 

Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂

<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rpire** [comment]
Hello, @rloterh 👋

Thank you for reviewing my work! I will proceed to merge these changes into the `dev` branch. 🚀

Cheers and Happy coding to you too! 🤓

**Pull request merged**
